### ISSUE TITLE
'&rsaquo;'  can't be  unescaped to HTML

### ISSUE THREAD

**Issue by jihonghai** [sant123/vuejs-uib-pagination#1]
Hi!
When I use this plugin in template,  the text like '&rsaquo;' can't be  unescaped to HTML.
The code is 
` <uib-pagination @change="fetch(pagination.currentPage)" :boundary-links="true" :total-items="totalItems" v-model="pagination" class="pagination-sm" 
                         previous-text="&lsaquo;" next-text="&rsaquo;" first-text="&laquo;" last-text="&raquo;" :max-size="5" :rotate="true" :force-ellipses="true"></uib-pagination>`

and the result is like this 
![html](https://cloud.githubusercontent.com/assets/6215226/26063877/dc4564fe-39c1-11e7-9543-b41b0d7fb513.jpeg)

**Comment by sant123** [comment]
Hi @jihonghai, have you reviewed the console output? Maybe there's an error telling you what's happening. If not, try changing the encoding to UTF-8.

**Comment by sant123** [comment]
However, could you post an example? Maybe at [Codepen](http://codepen.io/) or [Plunker](https://plnkr.co/).

**Comment by jihonghai** [comment]
@sant123  I use this plugin in Node. I post an example to Github [https://github.com/jihonghai/vuejs-uib-pagination-issue.git](https://github.com/jihonghai/vuejs-uib-pagination-issue.git) .  I use the plugin in 'src/pages/Dashboard.vue'.

**Comment by sant123** [comment]
@jihonghai when you use the *.vue template you can write the character literally. You do not need to escape it, that's why I encourage you to use this:

``` HTML
<uib-pagination  @change="fetch()" :boundary-links="true" :total-items="totalItems" v-model="pagination" class="pagination-sm" 
                         previous-text="‹" next-text="›" first-text="«" last-text="»" :max-size="5" :rotate="true" :force-ellipses="true"></uib-pagination>
```
