### ISSUE TITLE
Add "page-label" property support to render raw html 

### ISSUE THREAD

**Issue by feload** [sant123/vuejs-uib-pagination#11]
Hi

I would like to know if there's an option to render raw HTML when using page-label. 
That's because I need to render an icon instead of a number while retrieving data from the server.

Willing to help on this as needed.

Thank you very much.

**Comment by sant123** [comment]
Hi @feload, thank you for the issue. 
Reviewing your pull request there are some changes I need you make first. After that, I'll merge them.

**Comment by sant123** [comment]
https://github.com/sant123/vuejs-uib-pagination/pull/12

**Comment by sant123** [comment]
Merged.

**Comment by sant123** [comment]
https://github.com/sant123/vuejs-uib-pagination/pull/13

**Comment by feload** [comment]
Yes! Thank you!
