### ISSUE TITLE
How to apply the pagination

### ISSUE THREAD

**Issue by vrrb** [sant123/vuejs-uib-pagination#18]
I'm not sure how to implement this on my app. Let's say I have an array of items called `Items` how would I implement this plugin to work on my Items array?

**Comment by sant123** [comment]
Did you see the [Demo](https://plnkr.co/edit/hcfYWCTaQ7GnlO7AitGM?p=preview&preview) in Plunkr? Take a look at script.js.

**Comment by vrrb** [comment]
I did, but I can't see anywhere any v-for to iterate through my items or how to apply pagination to my existing array.

**Comment by sant123** [comment]
Well, that implementation needs to be done by your side. This is just a plugin that shows a pagination banner below your data. However you can follow this script that may help you in what you need:

``` js
export function paginateItems(items, currentPage, itemsPerPage) {
  const start = currentPage * itemsPerPage - itemsPerPage;
  const end = currentPage * itemsPerPage;

  return items.slice(start, end);
}

const data = [
    1,2,3,
    4,5,6,
    7,8,9,
];

// Suppose you are going to show 2 items per page and you are in the 3rd page.

const pageData = paginateItems(data, 3, 2);

console.log(pageData); // [ 5, 6 ]

```

That `pageData` will be in your v-for directive. Hope it helps.

**Comment by vrrb** [comment]
It helps. thanks!
