### ISSUE TITLE
Incorrect use of role attribute on page list items

### ISSUE THREAD

**Issue by hidanielle** [sant123/vuejs-uib-pagination#8]
Currently:
`<ul>` has no `role` attribute
`<li>` items have `role="menu"`

Expected
`<ul>` should have `role="menu"`
`<li>` items have `role="menuitem"`

**Comment by sant123** [comment]
Hi! And thank you for reporting this issue. PR is welcome ☺

**Comment by sant123** [comment]
Fixed! https://github.com/sant123/vuejs-uib-pagination/pull/9
